### ISSUE TITLE
Login UI (team FE)

### ISSUE THREAD

**Issue by lequanglocdev** [dunh-real/MockProject_112024#2]
**Feel free to choose any language that you know.**

**Comment by tranthanh02** [comment]
![image](https://github.com/user-attachments/assets/5f158bf4-3784-4c63-9a38-19a52708a4fc)

**Comment by worty76** [comment]
ReactJS styled with Material Tailwind.

![image](https://github.com/user-attachments/assets/79c8e40d-febd-43ff-9b04-fe46c1f428e4)

**Comment by Minhthien4** [comment]
![Screenshot 2024-11-08 154818](https://github.com/user-attachments/assets/8c7dfe8c-d68e-4d17-9970-633e213acde0)

**Comment by lequanglocdev** [comment]
![image](https://github.com/user-attachments/assets/8eb97ba0-58d7-4401-a5fb-48e5a99da464)

**Comment by nttdung0605** [comment]
![Screenshot 2024-11-08 173001](https://github.com/user-attachments/assets/44823e8d-3797-41b6-b159-4040350663aa)

**Comment by PhuocVinhLee** [comment]
ReactJS styled with Material  not Tailwind.

![image](https://github.com/user-attachments/assets/0fd66968-cd76-4a37-850e-137f47e4113e)

**Comment by phuquy2612** [comment]
![Uploading Ảnh chụp màn hình 2024-11-08 153221.png…]()

**Comment by phuquy2612** [comment]
![Ảnh chụp màn hình 2024-11-08 153221](https://github.com/user-attachments/assets/5a075aa7-9d92-45f0-a07b-f7125b48f907)

**Comment by phuquy2612** [comment]
![Ảnh chụp màn hình 2024-11-08 184708](https://github.com/user-attachments/assets/47b9a869-8f98-48b4-9ac6-3989f2c3460e)

**Comment by Minhtuan1235** [comment]
![Screenshot (497)](https://github.com/user-attachments/assets/b6e9f20e-a7ec-4b92-bfa6-63284e9845b7)

**Comment by Neverday10** [comment]
![Screenshot 2024-11-10 225701](https://github.com/user-attachments/assets/34474afb-775a-4445-9e1c-94193869c755)

**Comment by NguyenTheAnh1803** [comment]
![Sign in](https://github.com/user-attachments/assets/3db9dc25-7826-4863-ab28-b260c64c3771)
